INSERT INTO laboratorio.AREA VALUES ('USUARIOS1', 'USUARIOS 1', 25);
insert into laboratorio.area values ('USUARIOS2', 'USUARIOS 2', 30);
INSERT INTO laboratorio.AREA VALUES ('USUARIOS3', 'USUARIOS 3', 35);
INSERT INTO laboratorio.AREA VALUES ('USUARIOS4', 'USUARIOS 4', 25);
INSERT INTO laboratorio.AREA VALUES ('USUARIOS5', 'USUARIOS 5', 30);
INSERT INTO laboratorio.AREA VALUES ('USUARIOS6', 'USUARIOS 6', 40);
INSERT INTO laboratorio.AREA VALUES ('LABREDES', 'LABORATORIO DE REDES', 25);
INSERT INTO laboratorio.AREA VALUES ('LABBD', 'LABORATORIO DE BASES DE DATOS', 40);
INSERT INTO laboratorio.AREA VALUES ('ALMACEN', 'ALMACEN DE EQUIPOS LISTOS', 100);
INSERT INTO laboratorio.AREA VALUES ('DESCOMPUESTO', 'ALMACEN DE EQUIPOS DESCOMPUESTOS', 100);


