CREATE TABLE PERSONA(
	IDPERSONA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL,
    AP_PA VARCHAR(20) NOT NULL,
    AP_MA VARCHAR(20) NOT NULL,
    ESTADO VARCHAR(20)DEFAULT NULL CHECK (`ESTADO` in ('ALTA','BAJA')),
    FECHA_ALTA DATE
);
CREATE TABLE DEPARTAMENTO(
	IDDEPTO INT(6) AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    PRIMARY KEY(IDDEPTO)
);
CREATE TABLE CARRERA(
    IDDEPTO INT REFERENCES DEPARTAMENTO(IDDEPTO),
    IDCARRERA VARCHAR(6),
    NOMBRE VARCHAR(100),
    CONSTRAINT PK_CARR PRIMARY KEY(IDDEPTO,IDCARRERA)
);
CREATE TABLE ALUMNO(
    IDPERSONA INT REFERENCES PERSONA(IDPERSONA),
    NOCONTROL VARCHAR(9),
    IDDEPTO INT(6),
    IDCARRERA VARCHAR(6),
    SEMESTRE INT(2),
    CONSTRAINT PK_ALUMNO PRIMARY KEY(IDPERSONA),
    FOREIGN KEY (IDDEPTO,IDCARRERA) REFERENCES CARRERA(IDDEPTO,IDCARRERA)
);
CREATE TABLE DOCENTE(
    IDPERSONA INT REFERENCES PERSONA(IDPERSONA),
    NOTARJETA VARCHAR(9),
    IDDEPTO INT(6) REFERENCES DEPARTAMENTO(IDDEPTO),
    SEMESTRE INT(2),
    PRIMARY KEY(IDPERSONA)
);
CREATE TABLE PERSONAL(
    IDPERSONA INT REFERENCES PERSONA(IDPERSONA),
    NOTARJETA VARCHAR(9),
    IDDEPTO INT(6) REFERENCES CARRERA(IDDEPTO),
    PUESTO VARCHAR(20) DEFAULT NULL CHECK (`PUESTO` in ('ENCARGADO','AUXILIAR')),
    TURNO VARCHAR(20)DEFAULT NULL CHECK (`TURNO` in ('MATUTINO','VESPERTINO', 'MIXTO')),
    PRIMARY KEY(IDPERSONA)
);
CREATE TABLE USUARIO(
    IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(9),
    CONTRASENIA VARBINARY(20),
    ROL VARCHAR(20)DEFAULT NULL CHECK (`ROL` in ('DOCENTE','ADMINISTRADOR', 'AUXILIAR')),
    IDPERSONA INT REFERENCES PERSONA(IDPERSONA)
);
CREATE TABLE MATERIA(
	CLAVE VARCHAR(10) PRIMARY KEY,
    IDDEPTO INT(6), 
    IDCARRERA VARCHAR(5),
    RETICULA VARCHAR(20),
    FOREIGN KEY (IDDEPTO,IDCARRERA) REFERENCES CARRERA(IDDEPTO,IDCARRERA)
);
CREATE TABLE AREA(
	IDAREA INT PRIMARY KEY AUTO_INCREMENT,
    ALIASAREA  VARCHAR(15),
    CAPACIDAD INT,
    DESCRIPCION VARCHAR(50)
);
CREATE TABLE GRUPO(
    CLAVEGRUPO VARCHAR(15) PRIMARY KEY,
    CLAVE VARCHAR(10) REFERENCES MATERIA(CLAVE),
    DOCENTE INT REFERENCES DOCENTE(IDPERSONA),
    NOALUMNOS INT,
    HORA VARCHAR(20)
);
CREATE TABLE DETALLEGRUPO(
	CLAVEGRUPO VARCHAR(15) REFERENCES GRUPO(CLAVEGRUPO),
    IDPERSONA INT REFERENCES ALUMNO(IDPERSONA)
);
CREATE TABLE PRACTICA(
	FOLIOPRACTICA INT PRIMARY KEY AUTO_INCREMENT,
    NOM_PRACTICA VARCHAR(30),
    FECHA DATE, 
    DURACION INT,
    CLAVE VARCHAR(10) REFERENCES MATERIA(CLAVE),
    CLAVEGRUPO VARCHAR(15) REFERENCES GRUPO(CLAVEGRUPO)
);
CREATE TABLE HISTORIAL(
	FOLIOHIST INT PRIMARY KEY AUTO_INCREMENT,
    FOLIOPRACTICA INT REFERENCES PRACTICA(FOLIOPRACTICA),
    TIPO VARCHAR(20)DEFAULT NULL CHECK (`TIPO` in ('ALTA','ACTUALIZACION', 'BAJA')),
    FECHA DATE
);

CREATE TABLE EQUIPO(
    FOLIOINV VARCHAR(40),
    NOSERIE INT(30),
    MARCA VARCHAR(30),
    TIPO VARCHAR(30),
    FOLIOCPU VARCHAR(40),
    IDAREA INT REFERENCES AREA(IDAREA)
);

CREATE TABLE SOFTWARE(
	IDSOFTWARE INT PRIMARY KEY,
    SOFTWARE VARCHAR(30)
);

CREATE TABLE INVENTARIO(
	IDINV INT PRIMARY KEY AUTO_INCREMENT,
    FOLIOINV INT REFERENCES EQUIPO(FOLIOINV),
    TIPO VARCHAR(20)DEFAULT NULL CHECK (`TIPO` in ('ALTA','ACTUALIZACION', 'BAJA')),
    FECHA DATE
);